    // Buffs to track
    const targetBuffs = [
        'Seal of Command',
        'Nature\'s Grace',
        'Misdirection',
        'Seal of Righteousness',
        'Seal of Wisdom',
        'Stealth',
        'Flurry',
        'Sanctity Aura',
        'Demonic Frenzy',
        'Slice and Dice',
        'Seal of Blood',
        'Blessing of the Silver Crescent',
        'Furor',
        'Lifebloom',
        'Spell Haste',
        'Prayer of Mending',
        'Earth Shield',
        'Exploited Weakness',
        'Battle Shout',
        'Vengeance',
        'Clearcasting',
        'Electrical Charge',
        'Power of Arcanagos',
        'Focused',
        'Unleashed Rage',
        'Recklessness'
    ];
