// Debuffs to track
    const targetDebuffs = [
        'Insect Swarm',
        'Faerie Fire',
        'Mangle (Bear)',
        'Mangle (Cat)',
        'Demoralizing Roar',
        'Faerie Fire (Feral)',
        'Scorpid Sting',
        'Hunter\'s Mark',
        'Expose Weakness',
        'Scorch',
        'Judgement of Light',
        'Judgement of Wisdom',
        'Seal of the Crusader',
        'Shadow Weaving',
        'Vampiric Embrace',
        'Vampiric Touch',
        'Misery',
        'Expose Armor',
        'Hemorrhage',
        'Stormstrike',
        'Curse of Recklessness',
        'Curse of the Elements',
        'Curse of Weakness',
        'Shadow Embrace',
        'Improved Shadow Bolt',
        'Sunder Armor',
        'Demoralizing Shout',
        'Thunder Clap',
        'Blood Frenzy'
    ];
