const abilityIcons = {
    'Insect Swarm': 'spell_nature_insectswarm',
    'Faerie Fire': 'spell_nature_faeriefire',
    'Mangle (Bear)': 'ability_druid_mangle',
    'Mangle (Cat)': 'ability_druid_mangle2',
    'Demoralizing Roar': 'ability_druid_demoralizingroar',
    'Faerie Fire (Feral)': 'spell_nature_faeriefire',
    'Scorpid Sting': 'ability_hunter_criticalshot',
    'Hunter\'s Mark': 'ability_hunter_snipershot',
    'Expose Weakness': 'ability_rogue_findweakness',
    'Scorch': 'spell_fire_soulburn',
    'Judgement of Light': 'spell_holy_healingaura',
    'Judgement of Wisdom': 'spell_holy_righteousnessaura',
    'Seal of the Crusader': 'spell_holy_holysmite',
    'Shadow Weaving': 'spell_shadow_blackplague',
    'Vampiric Embrace': 'spell_shadow_unsummonbuilding',
    'Vampiric Touch': 'spell_holy_stoicism',
    'Misery': 'spell_shadow_misery',
    'Expose Armor': 'ability_warrior_riposte',
    'Hemorrhage': 'spell_shadow_lifedrain',
    'Stormstrike': 'ability_shaman_stormstrike',
    'Curse of Recklessness': 'spell_shadow_unholystrength',
    'Curse of the Elements': 'spell_shadow_chilltouch',
    'Curse of Weakness': 'spell_shadow_curseofmannoroth',
    'Shadow Embrace': 'spell_shadow_shadowembrace',
    'Improved Shadow Bolt': 'spell_shadow_improvedshadowbolt',
    'Sunder Armor': 'ability_warrior_sunder',
    'Demoralizing Shout': 'ability_warrior_warcry',
    'Thunder Clap': 'spell_nature_thunderclap',
    'Blood Frenzy': 'ability_warrior_bloodfrenzy'
};
